### ISSUE TITLE
Evaluation script

### ISSUE THREAD

**Issue by willxxy** [moein-shariatnia/Pix2Seq#1]
<img width="449" alt="Screen Shot 2022-08-19 at 2 41 29 PM" src="https://user-images.githubusercontent.com/90741489/198146538-cbbab014-e127-4454-a68c-a6720d9a4b7c.png">
Hi Moein, awesome implementation. 

I was wondering if you had the script for evaluating the results like in the png above. 

Thank you!

**Comment by moein-shariatnia** [comment]
Hi,
I'm glad it has been helpful.
Here's a [link](https://www.kaggle.com/code/moeinshariatnia/pix2seq-eval-new/notebook) to one of my experimental notebooks on Kaggle where I had implemented this evaluation too. 

Hope it helps.

**Comment by willxxy** [comment]
Thank you so much! closing the issue.
